import type { Metadata } from "next";
import { Inter , Roboto , Kantumruy_Pro} from "next/font/google";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300" , "400", "500",  "700", "900"],
});

const kantunruy = Kantumruy_Pro({
    subsets: ["latin"],
    variable: "--font-kantunruy",
    weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kantunruy.className}>{children}</body>
    </html>
  );
}
